src/portfolio/urls.py
from django.urls import path 
from .views import (
    portfolio,facturacion,whappip,wiki,marketing,landing
) 

app_name = 'portfolio'

urlpatterns = [
    path('portfolio/', portfolio, name='portfolio'),
    path('facturacion/', facturacion, name='facturacion'),
    path('whappip/', whappip, name='whappip'),
    path('wiki/', wiki, name='wiki'),
    path('marketing/', marketing, name='marketing'),
    path('landing/', landing, name='landing'),

]

src/task/urls.py
from django.urls import path 
from .views import (
    home_view,
    task_list,
    create_task,
    delete_task,
    edit_task,
    config,
    del_project,
    report,
) 

app_name = 'task'

urlpatterns = [
    path('', home_view, name='home'),
    path('list/', task_list, name='task_list'),
    path('new/', create_task, name='create_task'),
    path('edit/<int:task_id>/', edit_task, name='edit_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
    path('config/', config, name='config'),
    path('del_project/<int:id>', del_project, name='del_project'),
    path('report/', report, name='report'),
]

src/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from task.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace= 'task')),
    path('', include('portfolio.urls', namespace= 'portfolio')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", logout_view, name='logout' ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Report app | {% block title %}{% endblock title %}</title>
  </head>
  <body id="tasks">
    {% include 'navbar.html' %}
    <div class="container-fluid">
      {% if messages %}
        <div class="container-fluid fixed-bottom">
          <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-4">
              {% for message in messages %}
                <div class="alert 
                  {% if message.tags == 'error' %}
                    alert-danger
                  {% else %}
                    alert-{{ message.tags }} 
                  {% endif %}
                    alert-dismissible fade show auto-close"  id="alert-msg" role="alert">
                  <strong>{{ message }}</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      {% endif %}
        <div class="row my-0 mx-0 py-0 px-0">
          
          {% include "sidebar.html" %}
          <main role="main" class="col-md-11 col-lg-11 py-0 px-0 my-0 mx-0">
      {% block content %}
      
      {% endblock content %}
      </main>
      </div>
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="{% static  'js/scripts.js'%}"></script>
    <script>
      setTimeout(function() {
          bootstrap.Alert.getOrCreateInstance(document.querySelector("#alert-msg")).close();
      }, 3000);
      /* global bootstrap: false */
      (() => {
        'use strict'
        const tooltipTriggerList = Array.from(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        tooltipTriggerList.forEach(tooltipTriggerEl => {
          new bootstrap.Tooltip(tooltipTriggerEl)
        })
      })();
  </script>
  </body>
</html>

src/templates/create_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Crear
{% endblock title %}

{% block content %}
<section class="mt-3">
    <h5 class="text-center">
       {{ titulo }}
    </h5>
    <div class="container position-relative">
        <div class="container my-3 my-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-6 shadow-sm mx-auto bg-light py-2">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.title }}
                            <label for="floatingInput">Título</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.description }}
                            <label for="floatingTextarea">Descripción</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.project }}
                            <label for="floatingSelect">Proyecto</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.date }}
                            <label for="floatingInput2">Fecha de entrega</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.assigned_to }}
                            <label for="floatingSelect">Asignado a</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.state }}
                            <label for="floatingSelect2">Estado</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.priority }}
                            <label for="floatingSelect4">Prioridad</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.comments }}
                            <label for="floatingTextarea2">Comentarios</label>
                        </div>
                        <div class="d-grid gap-2 col mx-auto">
                            <button class="btn btn-lg btn-primary" type="submit">Guardar</button>
                            <a class="btn btn-lg btn-success" href="{% url 'task:home' %}">Regresar</a>
                        </div>
                       
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

src/templates/delete_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Borrar
{% endblock title %}

{% block content %}
<section class="mt-3">
    <h5 class="text-center">
       Confirmar borrado de tarea
    </h5>
    <div class="container position-relative">
        <div class="container my-3 my-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-6 shadow-sm mx-auto bg-light py-2">
                    <div class="alert alert-warning" role="alert">
                        ¿Está segur@ de querer borrar esta tarea?
                      </div>
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.title }}
                            <label for="floatingInput">Título</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.description }}
                            <label for="floatingTextarea">Descripción</label>
                        </div>
                        <div class="d-grid gap-2 col mx-auto">
                            <button class="btn btn-lg btn-danger" type="submit">Confirmar</button>
                            <a class="btn btn-lg btn-success" href="{% url 'task:home' %}">Regresar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

src/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Apps
{% endblock title %}

{% block content %}
<section class="mt-3">
    <div class="container position-relative">
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Mis Aplicaciones</h1>
            <p class="fs-5 text-body-secondary">Acceso directo a las aplicaciones, algunas están en fase beta y otras en desarrollo.</p>
          </div>
         <div class="row row-cols-1 row-cols-md-5 mb-3 justify-content-center text-center">
            <div class="col"> 
              <div class="card mb-4 rounded-3 shadow-sm">
                <a class="card_link" href="{% url 'task:task_list' %}">
                <div class="card-body">
                    <img class="rounded mx-auto d-block" style="width:150px;" src="{% static 'img/todo_app_01.jpg' %}" alt="mdo">
                    <h5 class="my-3 fw-normal">To-do app</h4>
                </div>
                </a>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 rounded-3 shadow-sm">
                <a class="card_link" href="{% url 'portfolio:facturacion' %}">
                  <div class="card-body">
                    <img class="rounded mx-auto d-block" style="width:150px;"  src="{% static 'img/facturacion.jpg' %}" alt="mdo">
                    <h5 class="my-3 fw-normal">Facturación</h5>
                  </div>
                </a>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 rounded-3 shadow-sm">
                <a class="card_link" href="{% url 'portfolio:portfolio' %}">
                  <div class="card-body">
                    <img class="rounded mx-auto d-block" style="width:150px;" src="{% static 'img/portafolio.jpg' %}" alt="mdo">
                    <h5 class="my-3 fw-normal">Portafolio</h5>
                  </div>
                </a>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 rounded-3 shadow-sm">
                <a class="card_link" href="{% url 'portfolio:whappip' %}">
                  <div class="card-body">
                    <img class="rounded mx-auto d-block" style="width:150px;" src="{% static 'img/whappip02.jpg' %}" alt="mdo">
                    <h5 class="my-3 fw-normal">Whappip</h5>
                  </div>
                </a>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 rounded-3 shadow-sm">
                <a class="card_link" href="{% url 'portfolio:wiki' %}">
                  <div class="card-body">
                    <img class="rounded mx-auto d-block" style="width:150px;" src="{% static 'img/wiki.jpg' %}" alt="mdo">
                    <h5 class="my-3 fw-normal">Wiki</h5>
                  </div>
                </a>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 rounded-3 shadow-sm">
                <a class="card_link" href="{% url 'portfolio:marketing' %}">
                  <div class="card-body">
                    <img class="rounded mx-auto d-block" style="width:150px;" src="{% static 'img/marketing03.jpg' %}" alt="mdo">
                    <h5 class="my-3 fw-normal">Marketing</h5>
                  </div>
                </a>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 rounded-3 shadow-sm">
                <a class="card_link" href="{% url 'portfolio:landing' %}">
                  <div class="card-body">
                    <img class="rounded mx-auto d-block" style="width:150px;" src="{% static 'img/landing.jpg' %}" alt="mdo">
                    <h5 class="my-3 fw-normal">Landing page</h5>
                  </div>
                </a>
              </div>
            </div>
          </div>
    </div>
</section>
{% endblock content %}

src/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <a href="{% url 'task:home' %}"><img width="60" height="" alt="logo" src="{% static 'img/logo.png' %}" class="logo-sm"></a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'task:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Menu</a>
        </li>
      </ul>
    </div>
    {% if request.user.is_authenticated %}
      <div class="nav-item dropdown text-light">
        <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="{% static 'img/avatar.png' %}" alt="avatar" style="width:40px;height:40px;" class="">&nbsp;{{request.user}}
        </div>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'portfolio:portfolio' %}">Profile</a></li>
          <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>

src/templates/sidebar.html
{% load static %}
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
    <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
  </symbol>
</svg>
<div class="sidebar border border-right col-md-1 col-lg-1 p-0 bg-body-tertiary" style="width: 4.7rem; height=90vh;max-height: 90vh;">
  <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
      <div id="sidebar-main" class="d-flex flex-column flex-shrink-0 bg-body-tertiary">
        <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
          <li class="nav-item">
            <a href="{% url 'task:home' %}" class="nav-link py-3 border-bottom rounded-0" aria-current="page" title="Home" data-bs-toggle="tooltip" data-bs-placement="right">
              <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Home"><use xlink:href="#home"/></svg>
            </a>
          </li>
          <li>
            <a href="#" class="nav-link py-3 border-bottom rounded-0" title="Dashboard" data-bs-toggle="tooltip" data-bs-placement="right">
              <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Dashboard"><use xlink:href="#speedometer2"/></svg>
            </a>
          </li>
          <li>
            <a href="#" class="nav-link py-3 border-bottom rounded-0" title="Orders" data-bs-toggle="tooltip" data-bs-placement="right">
              <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Orders"><use xlink:href="#table"/></svg>
            </a>
          </li>
          <li>
            <a href="#" class="nav-link py-3 border-bottom rounded-0" title="Products" data-bs-toggle="tooltip" data-bs-placement="right">
              <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Products"><use xlink:href="#grid"/></svg>
            </a>
          </li>
          <li>
            <a href="#" class="nav-link py-3 border-bottom rounded-0" title="Customers" data-bs-toggle="tooltip" data-bs-placement="right">
              <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Customers"><use xlink:href="#people-circle"/></svg>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

src/templates/under_construction.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    Tareas
{% endblock title %}

{% block content %}
        <div class="container-fluid" style="">
            <img width="100%" class="img-fluid" style="width:100%;" src="{% static 'img/under_construction.png' %}" alt="mdo">
        </div>
{% endblock content %} 