src/task/urls.py
from django.urls import path 
from .views import (
    home_view,
    task_list,
    create_task,
    delete_task,
    edit_task,
    config,
    del_project,
    report,
) 

app_name = 'task'

urlpatterns = [
    path('', home_view, name='home'),
    path('list/', task_list, name='task_list'),
    path('new/', create_task, name='create_task'),
    path('edit/<int:task_id>/', edit_task, name='edit_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
    path('config/', config, name='config'),
    path('del_project/<int:id>', del_project, name='del_project'),
    path('report/', report, name='report'),
]

src/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from task.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace= 'task')),
    path('', include('portfolio.urls', namespace= 'portfolio')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", logout_view, name='logout' ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/task/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Task(models.Model):
    STATUS_CHOICES = [
        ('TO_DO', 'TO DO'),
        ('IN_PROGRESS', 'IN PROGRESS'),
        ('DONE', 'DONE'),
    ]
    PRIORITY_CHOICES = [
        ('LOW', 'LOW'),
        ('MEDIUM', 'MEDIUM'),
        ('HIGH', 'HIGH'),
    ]
    
    title = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField()
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='TO_DO')
    comments = models.TextField(blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    priority = models.CharField(max_length=40, choices=PRIORITY_CHOICES, default='LOW')
    

    def __str__(self):
        return self.title
    


        

src/task/forms.py
from django import forms
from .models import Task, Project

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'project', 'date', 'assigned_to', 'status','priority', 'comments']
        widgets = {
            'title' : forms.TextInput(
                attrs={
                'class': 'form-control',
                'id': 'floatingInput',
            }),
            'description' : forms.Textarea(
                attrs={
                'class': 'form-control',
                'id': 'floatingTextarea',
                'style': 'height: 150px'
                }
            ),
            'project' : forms.Select(
                attrs={
                'class': 'form-select',
                'id': 'floatingSelect3',
                'aria-label': '',
                }
            ),
            'date': forms.TextInput  (
                attrs={
                'class': 'form-control',
                'id': 'floatingInput2',
                'type': 'date'
                }
            ),
            'assigned_to' : forms.Select(
                attrs={
                'class': 'form-select',
                'id': 'floatingSelect',
                'aria-label': '',
                }
            ),
            'status': forms.Select(
                attrs={
                    'class': 'form-select',
                    'id': 'floatingSelect2',
                }
            ),
            'priority': forms.Select(
                attrs={
                    'class': 'form-select',
                    'id': 'floatingSelect4',
                }
            ),
            'comments' : forms.Textarea(
                attrs={
                'class': 'form-control',
                'id': 'floatingTextarea2',
                'style': 'height: 200px'
                }
            ),
        }

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name']
        widgets = {
            'name' : forms.TextInput(
                attrs={
                'class': 'form-control',
                'id': 'floatingInput',
            }),
        }
        

src/task/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.db.models import Count
from .models import Task, Project
from .forms import TaskForm, ProjectForm
from datetime import datetime
from datetime import timedelta


def set_messages(request):
    five_days = datetime.now() + timedelta(days=5)
    overdue_tasks = Task.objects.filter(status__in =['TO_DO','IN_PROGRESS'], date__lte= datetime.now()).count()
    messages.error(request,'Tareas expiradas: '+ str(overdue_tasks))
    print("tareas expiradas: ", overdue_tasks)
    tasks_expiring = Task.objects.filter(status__in =['TO_DO','IN_PROGRESS'], date__range = (datetime.now(), five_days)).count()
    print("tareas por vencer: ", tasks_expiring)
    messages.warning(request,'Tareas a punto de vencer: '+str(tasks_expiring))




@login_required
def home_view(request):
    return render(request, 'home.html')

#funcion para listar las tareas en la ventana principal, tiene filtros y opciones para el cambio de estado de las tareas. 
@login_required
def task_list(request):
    status = {'TO_DO':'TO DO','IN_PROGRESS':'IN PROGRESS','DONE':'DONE'}
    task = ''
    projects = ''
    set_messages(request)

    if request.method == 'GET':
        #actualiza el estado de la tarea cuando se mueve de columna o cuando en la ventana modal se cambia de estado la tarea
        if request.GET.get('value') in ['dragged', 'changed']:
            task = get_object_or_404(Task, id=request.GET.get('id'))
            task.status = request.GET.get('status')
            task.save()
        #filtra las tareas por usuario o por projecto.
        elif request.GET.get('value') == 'filtered':  
           
            filter_type = request.GET.get('filter_type')
            filter_value = request.GET.get('filter_value')
           
            if filter_type == 'filter_user':
                tasks = Task.objects.filter(assigned_to=filter_value).order_by('priority','date') 
            elif filter_type == 'filter_project':
                tasks = Task.objects.filter(project__id=filter_value).order_by('priority','date') 
            else:
                tasks = Task.objects.all().order_by('priority','date')
            projects = Project.objects.all()
            context = {'tasks': tasks, 'status': status, 'projects': projects}
            return render(request, 'task/list_task.html', context)
    
    tasks = Task.objects.all().order_by('priority','date') 
    projects = Project.objects.all()
    context = {'tasks': tasks, 'status': status, 'projects': projects }
    return render(request, 'task/list_task.html', context)

@method_decorator(login_required, name='dispatch') 
class ListTasksView(View):
    template_name = 'task/task_list.html'

    def get(self, request):
        tasks = Task.objects.filter(assigned_to=request.user)
        return render(request, self.template_name, {'tasks': tasks})

@login_required
def create_task(request):
    titulo = "Crear tarea"
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.assigned_to = request.user
            task.save()
            messages.success(request,'Tarea creada')
            return redirect('task:task_list')
    else:
        form = TaskForm()
    return render(request, 'task/create_task.html', {'form': form, 'titulo': titulo})

@login_required
def edit_task(request, task_id):
    titulo = "Editar tarea"
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            messages.success(request,'Tarea actualizada')
            return redirect('task:task_list')
    else:
        form = TaskForm(instance=task)
    return render(request, 'task/create_task.html', {'form': form, 'task': task, 'titulo': titulo})

@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        task.delete()
        messages.success(request,'Tarea borrada')
        return redirect("task:task_list")
    else:
        form = TaskForm(instance=task)
    return render(request, 'task/delete_task.html', {'form': form, 'task': task})

@login_required  
def config(request):
    project = Project.objects.all()
    User = get_user_model()
    users = User.objects.all()
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Proyecto creado')

    form = ProjectForm()
    authForm = UserCreationForm()
    return render(request, 'task/config.html', {'form': form, 'authForm':authForm, 'project':project, 'users':users})

@login_required  
def del_project(request, id):
    project = get_object_or_404(Project, pk=id)
    if request.method == 'POST':
        project.delete()
        messages.success(request,'Projecto borrado')
        return redirect("task:config")
    else:
        form = ProjectForm(instance=project)
    return render(request, 'task/delete_project.html', {'form': form, 'project':project})


@login_required 
def report(request):
    # Obtener el recuento de tareas por estado
    datos_reporte = Task.objects.values('status').annotate(total=Count('status'))

    # Preparar datos para gráfico de barras
    labels = [dato['status'] for dato in datos_reporte]
    valores = [dato['total'] for dato in datos_reporte]

    return render(request, 'task/report.html' , {'labels': labels, 'valores': valores})

def logout_view(request):
    logout(request)
    return redirect("task:home") 

src/templates/task/config.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Crear
{% endblock title %}

{% block content %}
<section class="mt-3">
    <h5 class="text-center">
       Configuración
    </h5>
    <div class="container position-relative">
        <div class="container my-3 my-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-6 shadow-sm mx-auto bg-light py-2">
                    <h6 class="text-center mb-3">
                        Lista de proyectos
                    </h6>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre del proyecto</th>
                            <th scope="col" class="text-center">Eliminar</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for proj in project %}
                        <tr>
                            <th scope="row">{{ proj.id }}</th>
                            <td>{{ proj.name }}</td>
                            <td class="text-center">
                              <a href="{% url 'task:del_project' proj.id %}" class="text-decoration-none text-danger">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                  </svg>
                              </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-6 shadow-sm mx-auto bg-light py-2">
                    <h6 class="text-center mb-3">
                        Crear un proyecto
                     </h6>
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.name }}
                            <label for="floatingInput">Nombre del proyecto</label>
                        </div>
                        <div class="d-grid gap-2 col mx-auto">
                            <button class="btn btn-lg btn-success" type="submit">Guardar</button>
                            <a class="btn btn-lg btn-primary" href="{% url 'task:task_list'%}">Regresar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

src/templates/task/create_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Crear
{% endblock title %}

{% block content %}
<section class="mt-3">
    <h5 class="text-center">
       {{ titulo }}
    </h5>
    <div class="container position-relative">
        <div class="container my-3 my-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-6 shadow-sm mx-auto bg-light py-2">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.title }}
                            <label for="floatingInput">Título</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.description }}
                            <label for="floatingTextarea">Descripción</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.project }}
                            <label for="floatingSelect">Proyecto</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.date }}
                            <label for="floatingInput2">Fecha de entrega</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.assigned_to }}
                            <label for="floatingSelect">Asignado a</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.status }}
                            <label for="floatingSelect2">Estado</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.priority }}
                            <label for="floatingSelect4">Prioridad</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.comments }}
                            <label for="floatingTextarea2">Comentarios</label>
                        </div>
                        <div class="d-grid gap-2 col mx-auto">
                            <button class="btn btn-lg btn-primary" type="submit">Guardar</button>
                            <a class="btn btn-lg btn-success" href="{% url 'task:task_list' %}">Regresar</a>
                        </div>
                       
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

src/templates/task/delete_project.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Borrar
{% endblock title %}

{% block content %}
<section class="mt-3">
    <h5 class="text-center">
       Confirmar borrado de Proyecto
    </h5>
    <div class="container position-relative">
        <div class="container my-3 my-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-6 shadow-sm mx-auto bg-light py-2">
                    <div class="alert alert-warning" role="alert">
                        ¿Está segur@ de querer borrar este proyecto?
                      </div>
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.name }}
                            <label for="floatingInput">Nombre</label>
                        </div>
                        <div class="d-grid gap-2 col mx-auto">
                            <button class="btn btn-lg btn-danger" type="submit">Confirmar</button>
                            <a class="btn btn-lg btn-success" href="{% url 'task:config' %}">Regresar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

src/templates/task/delete_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Borrar
{% endblock title %}

{% block content %}
<section class="mt-3">
    <h5 class="text-center">
       Confirmar borrado de tarea
    </h5>
    <div class="container position-relative">
        <div class="container my-3 my-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-6 shadow-sm mx-auto bg-light py-2">
                    <div class="alert alert-warning" role="alert">
                        ¿Está segur@ de querer borrar esta tarea?
                      </div>
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.title }}
                            <label for="floatingInput">Título</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.description }}
                            <label for="floatingTextarea">Descripción</label>
                        </div>
                        <div class="d-grid gap-2 col mx-auto">
                            <button class="btn btn-lg btn-danger" type="submit">Confirmar</button>
                            <a class="btn btn-lg btn-success" href="{% url 'task:task_list' %}">Regresar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

src/templates/task/report.html
{% extends 'base.html' %}

{% block content %}
<section class="mt-3">
    <h2 class="text-center">Reporte de Tareas por Estado</h2>
    <div class="container position-relative">
        <div class="container my-3 my-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-10 shadow-sm mx-auto bg-light py-2">
                    <div>
                        <canvas id="graficoTareas"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var ctx = document.getElementById('graficoTareas').getContext('2d');
      var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: {{ labels|safe }},
          datasets: [{
            label: 'Número de Tareas',
            data: {{ valores|safe }},
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
            ],
            borderColor: [
              'rgba(255, 99, 132, 1)',
              'rgba(54, 162, 235, 1)',
              'rgba(255, 206, 86, 1)',
            ],
            borderWidth: 1
          }]
        },
        options: {
          scales: {
            y: {
              beginAtZero: true
            }
          }
        }
      });
    });
  </script>
{% endblock %}